#!/usr/bin/env bash

CONFIG_FILE="$HOME/.config/db_connect.yaml"
SOPS_CONFIG_FILE="$HOME/.config/.sops.yaml"

declare -A COMMAND_MAP=(
  [clickhouse]=clickhouse-client
  [mysql]=mycli
  [postgres]=pgcli
  [mongodb]=mongosh
)

declare -A PORT_MAP=(
  [clickhouse]=9000
  [mysql]=3306
  [postgres]=5432
  [mongodb]=27017
)

declare -A INSTAL_MAP=(
  [yq]="https://github.com/mikefarah/yq?tab=readme-ov-file#install"
  [fzy]="https://github.com/jhawthorn/fzy?tab=readme-ov-file#installation"
  [sops]="https://github.com/getsops/sops#download"
  [gpg]="https://www.gnupg.org/download/"
  [mycli]="https://www.mycli.net/install"
  [pgcli]="https://www.pgcli.com/install"
  [clickhouse-client]="https://clickhouse.com/docs/install"
  [mongosh]="https://www.mongodb.com/docs/mongodb-shell/install/"
)

function install_error() {
  echo "\`$1\` is not installed, install from ${INSTAL_MAP[$1]}"
}

function require_cmd() {
  if ! command -v "$1" &>/dev/null; then
    install_error "$1"
    exit 1
  fi
}

help() {
  printf "
db_connect: keep connection configuration and connect to databases throug network
commands:
  init           : create config file [%s]
  add            : add config
  show [name]    : show while config or [name]
  delete {name}  : remove the {name} from config
  connect {name} : connect to database defined in {name}
  completion     : print bash completion
  help           : print this message and exit
supported databases: %s
supported tools    : %s
config is sops-encrypted with your GPG key; set SOPS_PGP_FP or be prompted on first \`init\`
install urls:
" "${CONFIG_FILE}" "${!PORT_MAP[*]}" "${COMMAND_MAP[*]}"

  printf "  %s\n" "${INSTAL_MAP[@]}"

}

function bash_completion() {
  # shellcheck disable=SC2016
  echo '_complete_db_connect() {
  local commands
  local items
  local prev
  declare -A commands=(
    [init]=1
    [show]=1
    [add]=1
    [delete]=1
    [connect]=1
    [completion]=1
    [help]=1
  )
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [ "${COMP_CWORD}" -eq "1" ]; then
    readarray -t COMPREPLY <<< "$(compgen -W "${!commands[*]}" -- "${COMP_WORDS[1]}")"
  elif [ "${COMP_CWORD}" -eq "2" ]
  then
      if ! [ "${commands[${prev}]}" ] || [ "${prev}" == "init" ] || [ "${prev}" == "help" ]
      then
        return
      else
        readarray -t items <<< "$(yq "(. | keys)[] | select(. != \"sops\")" "$HOME/.config/db_connect.yaml")"
        readarray -t COMPREPLY <<< "$(compgen -W "${items[*]}" -- "${COMP_WORDS[2]}")"
      fi
  else
    return
  fi
}

complete -F _complete_db_connect db_connect'
}

function init() {
  require_cmd yq
  require_cmd fzy
  require_cmd sops
  require_cmd gpg

  if ! [ -f "$SOPS_CONFIG_FILE" ]; then
    local fp="${SOPS_PGP_FP:-}"
    if ! [ "$fp" ]; then
      read -rp "GPG key fingerprint to encrypt config with: " fp
    fi
    : "${fp:?GPG fingerprint must be set (or export SOPS_PGP_FP)}"
    if ! gpg --list-keys "$fp" &>/dev/null; then
      echo "GPG key \`$fp\` not found in your keyring"
      exit 1
    fi
    cat > "$SOPS_CONFIG_FILE" <<EOF
creation_rules:
  - path_regex: db_connect.*\\.yaml$
    pgp: "$fp"
EOF
  fi

  if ! [ -f "$CONFIG_FILE" ]; then
    echo '{}' > "$CONFIG_FILE"
    sops --config "$SOPS_CONFIG_FILE" encrypt -i "$CONFIG_FILE"
    chmod 600 "$CONFIG_FILE"
  fi
}

function decrypt_to_tmp() {
  local tmp
  tmp="$(mktemp --suffix=.yaml -p "$(dirname "$CONFIG_FILE")" db_connect.XXXXXX)"
  chmod 600 "$tmp"
  if ! sops decrypt "$CONFIG_FILE" > "$tmp"; then
    rm -f "$tmp"
    exit 1
  fi
  echo "$tmp"
}

function encrypt_from_tmp() {
  local tmp="$1"
  sops --config "$SOPS_CONFIG_FILE" encrypt -i "$tmp"
  mv "$tmp" "$CONFIG_FILE"
}

function add_config() {
  local name host user pass port db db_type default_port is_srv
  read -rp "Config name: " name
  db_type="$(printf "%s\n" "${!COMMAND_MAP[@]}" | fzy --prompt='Select database type: ')"
  echo "Select database type: $db_type"
  default_port="${PORT_MAP[$db_type]}"
  if ! [ "${default_port}" ]; then
    echo "Database type not supported, should be one of: ${!PORT_MAP[*]}"
    exit 1
  fi
  read -rp "Database host [default: 127.0.0.1]: " host
  host="${host:-127.0.0.1}"
  read -rp "Is the host record SRV (default: no) [yes/no]: " is_srv
  is_srv="${is_srv,,}"
  if [ "${is_srv}" != 'no' ] && [ "${is_srv}" != "yes" ]; then
    is_srv='no'
  fi
  if [ "${is_srv}" == "no" ]; then
    read -rp "Database port [default: ${default_port}]: " port
    port="${port:-$default_port}"
  else
    port=""
  fi
  read -rp "Database user: " user
  : "${user:?Database user must be set}"
  read -rp "Connect database name: " db
  db="${db:-USE_DEFAULT}"
  read -rsp "Database password: " pass
  : "${pass:?Database password must be set}"
  echo
  local tmp
  tmp="$(decrypt_to_tmp)"
  trap 'rm -f "$tmp"' EXIT
  yq eval -i ".\"$name\".type = \"$db_type\"" "$tmp"
  yq eval -i ".\"$name\".host = \"$host\"" "$tmp"
  yq eval -i ".\"$name\".port = \"$port\"" "$tmp"
  yq eval -i ".\"$name\".user = \"$user\"" "$tmp"
  yq eval -i ".\"$name\".pass = \"$pass\"" "$tmp"
  yq eval -i ".\"$name\".is_srv = \"$is_srv\"" "$tmp"
  yq eval -i ".\"$name\".db = \"$db\"" "$tmp"
  encrypt_from_tmp "$tmp"
  trap - EXIT
}

function show_config() {
  if [ "$1" ]; then
    sops decrypt "$CONFIG_FILE" | yq -Poy ".$1"
  else
    sops decrypt "$CONFIG_FILE" | yq -Poy
  fi
}

function delete_config() {
  local tmp
  tmp="$(decrypt_to_tmp)"
  trap 'rm -f "$tmp"' EXIT
  yq eval -i "del(.$1)" "$tmp"
  encrypt_from_tmp "$tmp"
  trap - EXIT
}

function connect() {
  local name db_type host is_srv port user pass db cmd decrypted
  name="$1"
  shift
  if ! [ "$name" ]; then
    echo "Usage: db_connect connect {name} [extra args...]"
    exit 1
  fi
  decrypted="$(sops decrypt "$CONFIG_FILE")"
  if [ "$(yq ". | has(\"$name\")" <<< "$decrypted")" != "true" ]; then
    echo "Config \`$name\` does not exist"
    exit 1
  fi
  host="$(yq ".$name.host" <<< "$decrypted")"
  port="$(yq ".$name.port" <<< "$decrypted")"
  user="$(yq ".$name.user" <<< "$decrypted")"
  pass="$(yq ".$name.pass" <<< "$decrypted")"
  db_type="$(yq ".$name.type" <<< "$decrypted")"
  is_srv="$(yq ".$name.is_srv" <<< "$decrypted")"
  db="$(yq ".$name.db" <<< "$decrypted")"
  case "${db_type}" in
  clickhouse)
    cmd="clickhouse-client"
    cmd+=" --host $host"
    cmd+=" --user $user"
    cmd+=" --port $port"
    cmd+=" --password $pass"
    if [ "${db}" != 'USE_DEFAULT' ]; then
      cmd+=" --database $db"
    fi
    ;;
  mysql)
    cmd="mycli"
    cmd+=" -h $host"
    cmd+=" -u $user"
    cmd+=" -P $port"
    cmd+=" -p $pass"
    if [ "${db}" != 'USE_DEFAULT' ]; then
      cmd+=" -D $db"
    fi

    ;;
  postgres)
    PGPASSWORD="$pass"
    export PGPASSWORD
    cmd="pgcli"
    cmd+=" -h $host"
    cmd+=" -u $user"
    cmd+=" -p $port"
    if [ "${db}" != 'USE_DEFAULT' ]; then
      cmd+=" -d $db"
    fi
    ;;
  mongodb)
    cmd="mongosh"
    if [ "$is_srv" == 'yes' ]; then
      cmd+=" mongodb+srv://$user:$pass@$host/"
    else
      cmd+=" mongodb://$user:$pass:$host:$port/"
    fi
    if [ "${db}" != 'USE_DEFAULT' ]; then
      cmd+="$db"
    fi
    cmd+="?authSource=admin"
    ;;
  *)
    echo "Unsupported database type \`$db_type\` for config \`$name\`"
    exit 1
    ;;
  esac
  $cmd "$@"
}

case "${1}" in
init)
  init
  ;;
completion)
  bash_completion
  ;;
show)
  init
  show_config "$2"
  ;;
add)
  init
  add_config "$2" "$3"
  ;;
delete)
  init
  delete_config "$2"
  ;;
connect)
  init
  shift
  connect "$@"
  ;;
'-h' | '--help' | 'help')
  help
  exit
  ;;
*)
  echo -e "\n\033[01;31mError. Command not valid. Valid values are {init|completion|show|add|delete|connect}\033[00m\n"
  help
  exit 1
  ;;
esac
